# 服务器配置
server:
  port: 9001
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 2000
    accept-count: 2000
  servlet:
    context-path: /
# 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.194:8000/eureka/
  instance:
    prefer-ip-address: true
    appname: cloud-core

spring:
  main:
    allow-bean-definition-overriding: true
  # 数据源配置
  datasource:
    # 输入你自己数据源配置
    # hikari连接池配置
    hikari:
      connection-timeout: 30000
  # jpa配置
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect